#!/bin/bash
# CHANGELOG Generator - 生成规范化 CHANGELOG.md
# 用法: bash changelog.sh [repo_path]
# 默认使用当前仓库

REPO="${1:-.}"

cd "$REPO" || exit 1

# 获取上次 tag 之后的 commit
if git tag -l | grep -q .; then
  COMMITS=$(git log --pretty=format:"%s" $(git describe --tags --abbrev=0)..HEAD 2>/dev/null || echo "")
else
  COMMITS=$(git log --pretty=format:"%s" -20)
fi

# 分类函数
categorize() {
  local msg="$1"
  msg_lower=$(echo "$msg" | tr '[:upper:]' '[:lower:]')
  
  if echo "$msg_lower" | grep -qE "^(add|new|feat|feature|introduce|initial)"; then
    echo "Added"
  elif echo "$msg_lower" | grep -qE "^(fix|bug|patch|correct|repair)"; then
    echo "Fixed"
  elif echo "$msg_lower" | grep -qE "^(remove|delete|drop|uninstall)"; then
    echo "Removed"
  elif echo "$msg_lower" | grep -qE "^(update|upgrade|change|modify|refactor|optimize|improve)"; then
    echo "Changed"
  else
    echo "Changed"
  fi
}

# 生成 CHANGELOG
echo "# Changelog"
echo ""
echo "All notable changes to this project will be documented in this file."
echo ""
echo "## Unreleased"
echo ""

declare -A categories
categories["Added"]=""
categories["Fixed"]=""
categories["Changed"]=""
categories["Removed"]=""

while IFS= read -r line; do
  [ -z "$line" ] && continue
  cat=$(categorize "$line")
  categories["$cat"]+="- $line\n"
done <<< "$COMMITS"

for cat in Added Fixed Changed Removed; do
  if [ -n "${categories[$cat]}" ]; then
    echo "### $cat"
    echo -e "${categories[$cat]}"
  fi
done

echo "---"
echo "*Generated by changelog.sh*"
